### ISSUE TITLE
Recipe App Kanban Board

### ISSUE THREAD

**Issue by rmiyoyo** [rmiyoyo/recipe-app#15]
# Work Done
We have assigned each team member tasks to be completed within the set deadlines.

Link to the Kanban Board: [Kanban Board](https://github.com/users/rmiyoyo/projects/2)

## Team Members
1. Raphael Miyoyo @rmiyoyo 
2. Ismail Halliru Muhammad @yayaismaail 
3. Sami Ullah Tufail @Sami-Ullah-Tufail

**Comment by skyv26** [comment]
## Hi @rmiyoyo , @Sami-Ullah-Tufail and @yayaismaail , 

Your project is complete!  There is nothing else to say other than... it's time to start your project :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWRlMTU1MTgyOWI3OTNiMGUxOWQ3NTUxNDc4YWE5MTY0YWFmNmEwYyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Ti0pkgccBnF7Xy1vhk/giphy-downsized-large.gif)

## Highlights 
- Workload distribution is fair ✅

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rmiyoyo** [comment]
Thank you @skyv26 for the review. I will now mark issue #15 as closed.
